name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to BitBucket'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@bitbucket.org:creeper2077/nginx-php-git.git
          ssh_private_key:
            ${{ secrets.BACKUP_KEY }}

  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:Creeper2077/nginx-php-git.git
          ssh_private_key:
            ${{ secrets.BACKUP_KEY }}